name: Release a tag
description: This action allows to release a tag

inputs:
  release-type: 
    type: choice
    options:
      - auto
      - patch
      - minor
      - major
    default: auto
  tag:
    default: v0.0.0
  
runs:
  using: composite
  steps:
    - name: Print release-type
      run: echo ${{ inputs.release-type }}
      shell: bash