name: Release a tag
description: This action allows to release a tag

inputs:
  release-type: 
    type: choice
    options:
      - auto
      - patch
      - minor
      - major
    default: auto
  tag:
    default: v0.0.0
  
runs:
  using: composite
  steps:
    - name: Checkout with full history (tags, describe, changelogs)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  # Collect commits since last tag
  # If tag does not exist, get all commits
    - name: Get commits since last tag
      id: get-commits
      run: |
        LAST_TAG="${{ inputs.tag }}"
        echo "Last tag: $LAST_TAG"
        if [ "$LAST_TAG" = "v0.0.0" ]; then
          COMMITS=$(git log --pretty=format:"%s")
        else
          COMMITS=$(git log "$LAST_TAG"..HEAD --pretty=format:"%s")
        fi
        echo "Commits since last tag:"
        echo "$COMMITS"
        {
          echo "commits<<EOF"
          echo "$COMMITS"
          echo "EOF"
        } >> $GITHUB_OUTPUT
      shell: bash