name: Release a tag
description: This action allows to release a tag

inputs:
  release-type: 
    type: choice
    options:
      - auto
      - patch
      - minor
      - major
    default: auto
  tag:
    default: v0.0.0
  
runs:
  using: composite
  steps:
    - name: Checkout with full history (tags, describe, changelogs)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
  # Collect commits since last tag
  # If tag does not exist, get all commits
    - name: Get commits since last tag
      id: get-commits
      run: |
        LAST_TAG="${{ inputs.tag }}"
        echo "Last tag: $LAST_TAG"
        if [ "$LAST_TAG" = "v0.0.0" ]; then
          COMMITS=$(git log --pretty=format:"%s")
        else
          COMMITS=$(git log "$LAST_TAG"..HEAD --pretty=format:"%s")
        fi
        echo "$COMMITS" > commits.txt
      shell: bash
  # Get new release tag based on commits from last tag to main
  # Tag is of the format vX.Y.Z
  # X is major change, Y is minor change, Z is patch change  
  # 1. Traverse through each commit
  # 2. If any commit has "BREAKING CHANGE" in its message, consider it a major change. Increment X by 1 and reset Y and Z to 0
  # 3. Else if any commit starts with "feat:", consider it a minor change. Increment Y by 1 and reset Z to 0
  # else consider it a patch change. Increment Z by 1
    - name: Compute new tag
      id: compute-new-tag
      run: |
        LAST_TAG="${{ inputs.tag }}"
        RELEASE_TYPE="${{ inputs.release-type }}"
        echo "Last tag: $LAST_TAG"
        echo "Release type: $RELEASE_TYPE"
        
        # Remove 'v' prefix and split into components
        VERSION="${LAST_TAG#v}"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        
        # Set defaults if empty
        MAJOR="${MAJOR:-0}"
        MINOR="${MINOR:-0}"
        PATCH="${PATCH:-0}"
        
        echo "Analyzing commits..."
        
        # Check commits for breaking changes or features
        while IFS= read -r COMMIT; do
          echo "Processing commit: $COMMIT"
          if [[ "$COMMIT" == *"BREAKING CHANGE"* ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$COMMIT" == feat:* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi
        done < commits.txt
        
        NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"
        echo "New tag: $NEW_TAG"
        echo "new-tag=$NEW_TAG" >> $GITHUB_OUTPUT
      shell: bash