name: Building blocks
on: 
  push:
    paths:
      - '.github/workflows/building-blocks.yaml'
concurrency:
    group: building-blocks
    cancel-in-progress: false
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: |
          sudo apt-get -y install cmake
          whoami
          cmake --version
